service: uid2-api-wrapper
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  region: ${file(config.${self:provider.stage}.json):region}
  stage: ${opt:stage, 'dev'}
  environment:
    endpoint: ${file(config.${self:provider.stage}.json):endpoint}
    version: ${file(config.${self:provider.stage}.json):version}
    secret_name: ${file(config.${self:provider.stage}.json):secret_name}
    ip_white_list: ${file(config.${self:provider.stage}.json):ip_white_list}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "*"

plugins:
  - serverless-python-requirements

functions:
  uid2-sdk:
    handler: handler.uid2_sdk
    events:
      - http:
          method: get
          path: /uid2_sdk
  token-generate:
    handler: handler.token_generate
    events:
      - http:
          method: get
          path: /token/generate
